// <auto-generated />
namespace ReptileManager.Migrations.ReptileMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reptilesImagesInBlob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reptilesImagesInBlob));
        
        string IMigrationMetadata.Id
        {
            get { return "201510131510421_reptilesImagesInBlob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
